In [2]:
import numpy as np
import pandas as pd

- Numpy --> n-Dimensional array computation

- Pandas --> data format specificially designed for data analysis (Series dan DataFrame)

In [3]:
# NUMPY Exercise

- Soal 1
- Create a 2D array this_array which consists of these elements<br>
10 20 30 1<br>
40 50 60 2<br>
70 80 90 3<br>

In [24]:
my_list = [10, 20, 30, 1]
my_list2 = [40, 50, 60, 2]
my_list3 = [70, 80, 90, 3]

my_2d_list = [my_list, my_list2, my_list3]

this_array = np.array(my_2d_list)
this_array

array([[10, 20, 30,  1],
       [40, 50, 60,  2],
       [70, 80, 90,  3]])

In [6]:
# Soal 2
# How can we retrieve the elements in the 3rd column of the array?

In [7]:
this_array[:, 2]

array([30, 60, 90])

In [8]:
# Soal 3
# How can we retrieve 90  from the array

In [9]:
this_array[2, 2]

90

In [10]:
# Soal 4
# How can we retrieve the 2nd element of 1st and 2nd row from the array?

In [11]:
this_array[:2, 1]

array([20, 50])

In [12]:
# Soal 5
# How will happen if you substract the array with np.array([1, 2, 3])?

In [13]:
other_array = np.array([1, 2, 3])
this_array - other_array # tidak bisa di lakukan operasi matimatik jika jumlah baris dan kolom tidak sesuai
# minimial jumlah baris sama atau jumlah kolom sama

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [14]:
# Soal 6
# What will happen if you add the array with 7?

In [15]:
this_array + 7 # akan menambahkan 7 pada setiap elemen

array([[17, 27, 37,  8],
       [47, 57, 67,  9],
       [77, 87, 97, 10]])

In [16]:
# Soal 7
# What will happen if you execute new_array = np.concatenate((this_array, [[4, 5, 6, 7]]), axis = 0)?

In [17]:
new_array = np.concatenate((this_array, [[4, 5, 6, 7]]), axis = 0)

In [18]:
new_array

array([[10, 20, 30,  1],
       [40, 50, 60,  2],
       [70, 80, 90,  3],
       [ 4,  5,  6,  7]])

In [19]:
# Note: 
# Jika mau menambahkan baris (axis = 0) -->Jumlah kolom harus sama
# Jika mau menambahkan kolom (axis = 1) -->Jumlah baris harus sama

In [20]:
# PANDAS Exercise

In [21]:
df_restaurants = pd.read_csv('Top250.csv')
df_restaurants

Rank           Restaurant  \
0       1           McDonald's   
1       2            Starbucks   
2       3          Chick-fil-A   
3       4            Taco Bell   
4       5          Burger King   
..    ...                  ...   
245   246      Rainforest Cafe   
246   247                  PDQ   
247   248        Lupe Tortilla   
248   249  Cook-Out Restaurant   
249   250             Jollibee   

                                               Content  Sales YOY_Sales  \
0                                                  NaN  40412      4.9%   
1                                                  NaN  21380      8.6%   
2    While Popeyes got a lot of the chicken buzz in...  11320     13.0%   
3                                                  NaN  11293      9.0%   
4                                                  NaN  10204      2.7%   
..                                                 ...    ...       ...   
245                                                NaN    129    -10.4%   
246                                                NaN    127     -5.5%   
247                                                NaN    127     12.1%   
248                                                NaN    126     10.1%   
249                                                NaN    126     15.2%   

     Units YOY_Units Headquarters             Segment_Category  
0    13846     -0.5%          NaN       Quick Service & Burger  
1    15049      3.0%          NaN  Quick Service & Coffee Cafe  
2     2470      5.0%          NaN      Quick Service & Chicken  
3     6766      2.7%          NaN      Quick Service & Mexican  
4     7346      0.2%          NaN       Quick Service & Burger  
..     ...       ...          ...                          ...  
245     18     -5.3%          NaN                  Varied Menu  
246     56    -11.1%          NaN                      Chicken  
247     25      8.7%          NaN                      Mexican  
248    270      7.1%          NaN                       Burger  
249     40     11.1%          NaN                      Chicken  

[250 rows x 9 columns]

In [25]:
df_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Rank              250 non-null    int64 
 1   Restaurant        250 non-null    object
 2   Content           33 non-null     object
 3   Sales             250 non-null    int64 
 4   YOY_Sales         250 non-null    object
 5   Units             250 non-null    int64 
 6   YOY_Units         250 non-null    object
 7   Headquarters      52 non-null     object
 8   Segment_Category  250 non-null    object
dtypes: int64(3), object(6)
memory usage: 17.7+ KB


In [27]:
# Soal 1
# Replace / create a new column that converts YOY_Sales column into decimal format 
# (e.g. 4.9% (String)--> 0.049(Float), 13.0%-->0.13)

In [38]:
# float(df_restaurants['YOY_Sales'][0].replace('%', '')) / 100

# define a function, then apply it to every row
def convert_to_decimal(x):
    return float(x.replace('%', '')) / 100
    
df_restaurants['YOY_Sales'] =  df_restaurants['YOY_Sales'].apply(convert_to_decimal)
# define a lambda function, idem

In [39]:
df_restaurants

Rank           Restaurant  \
0       1           McDonald's   
1       2            Starbucks   
2       3          Chick-fil-A   
3       4            Taco Bell   
4       5          Burger King   
..    ...                  ...   
245   246      Rainforest Cafe   
246   247                  PDQ   
247   248        Lupe Tortilla   
248   249  Cook-Out Restaurant   
249   250             Jollibee   

                                               Content  Sales  YOY_Sales  \
0                                                  NaN  40412      0.049   
1                                                  NaN  21380      0.086   
2    While Popeyes got a lot of the chicken buzz in...  11320      0.130   
3                                                  NaN  11293      0.090   
4                                                  NaN  10204      0.027   
..                                                 ...    ...        ...   
245                                                NaN    129     -0.104   
246                                                NaN    127     -0.055   
247                                                NaN    127      0.121   
248                                                NaN    126      0.101   
249                                                NaN    126      0.152   

     Units YOY_Units Headquarters             Segment_Category  
0    13846     -0.5%          NaN       Quick Service & Burger  
1    15049      3.0%          NaN  Quick Service & Coffee Cafe  
2     2470      5.0%          NaN      Quick Service & Chicken  
3     6766      2.7%          NaN      Quick Service & Mexican  
4     7346      0.2%          NaN       Quick Service & Burger  
..     ...       ...          ...                          ...  
245     18     -5.3%          NaN                  Varied Menu  
246     56    -11.1%          NaN                      Chicken  
247     25      8.7%          NaN                      Mexican  
248    270      7.1%          NaN                       Burger  
249     40     11.1%          NaN                      Chicken  

[250 rows x 9 columns]

In [40]:
# Soal 2
# Retrieve the name of Quick Service & Mexican restaurants that are in rank 1-50

In [48]:
df_restaurants[
    (df_restaurants['Segment_Category'] == 'Quick Service & Mexican') 
    & (df_restaurants['Rank'].between(1, 50))
]

Rank Restaurant Content  Sales  YOY_Sales  Units YOY_Units Headquarters  \
3     4  Taco Bell     NaN  11293       0.09   6766      2.7%          NaN   

          Segment_Category  
3  Quick Service & Mexican

In [55]:
# Soal 3
# Retrieve the top 20 Quick Service & Burger Restaurants based on their YOY Sales.

In [60]:
df_restaurants[
    df_restaurants['Segment_Category'] == 'Quick Service & Burger'
].sort_values(by = 'YOY_Sales', ascending = False).iloc[:20]

Rank                     Restaurant  \
37    38                       Culver's   
29    30                    Whataburger   
0      1                     McDonald's   
12    13                 Sonic Drive-In   
49    50                In-N-Out Burger   
6      7                        Wendy's   
4      5                    Burger King   
75    76                   White Castle   
23    24                Jack in the Box   
84    85  Checkers Drive-In Restaurants   
42    43                     Carl's Jr.   
34    35                       Hardee's   
50    51                 Steak 'n Shake   

                                              Content  Sales  YOY_Sales  \
37  One of the country's fastest-growing chains ov...   1795      0.139   
29                                                NaN   2556      0.058   
0                                                 NaN  40412      0.049   
12  The drive-in chain grew same-store sales for t...   4687      0.046   
49                                                NaN    957      0.046   
6                                                 NaN   9762      0.042   
4                                                 NaN  10204      0.027   
75                                                NaN    579      0.024   
23                                                NaN   3504      0.011   
84                                                NaN    535     -0.018   
42                                                NaN   1423     -0.025   
34                                                NaN   2020     -0.040   
50  As of August, the chain had temporarily closed...    950     -0.077   

    Units YOY_Units Headquarters        Segment_Category  
37    732      6.7%          NaN  Quick Service & Burger  
29    830      0.6%          NaN  Quick Service & Burger  
0   13846     -0.5%          NaN  Quick Service & Burger  
12   3526     -2.1%          NaN  Quick Service & Burger  
49    351      3.5%          NaN  Quick Service & Burger  
6    5852      0.7%          NaN  Quick Service & Burger  
4    7346      0.2%          NaN  Quick Service & Burger  
75    371     -0.5%          NaN  Quick Service & Burger  
23   2243      0.3%          NaN  Quick Service & Burger  
84    584     -0.2%          NaN  Quick Service & Burger  
42   1095     -2.3%          NaN  Quick Service & Burger  
34   1820     -1.4%          NaN  Quick Service & Burger  
50    576     -3.0%          NaN  Quick Service & Burger

In [61]:
# Soal 4
# Calculate the average Sales in each restaurant category

In [65]:
df_restaurants.groupby('Headquarters')['Sales'].mean()

Headquarters
Addison, TX             297.500000
Atlanta, GA             335.000000
Austin, TX              349.000000
Birmingham, AL          290.000000
Boston, MA              289.000000
Chattanooga, TN         275.000000
Cheyenne, WY            373.000000
Coppell, TX             410.000000
Countryside, IL         338.000000
Dallas, TX              398.333333
Denver, CO              289.000000
Doral, FL               340.000000
Dunwoody, GA            343.000000
Emeryville, CA          357.000000
Houston, TX             312.333333
Irvine, CA              265.000000
Irving, TX              325.333333
Lexington, KY           275.000000
Louisville, KY          404.000000
Miami, FL               425.000000
Minneapolis, MN         306.000000
Minnetonka, MN          329.000000
Mission Viejo, CA       259.000000
Nashville, TN           426.000000
New York, NY            281.000000
Oklahoma City, OK       268.000000
Orange City, IA         269.000000
Orlando, FL             253.000000
Pasaden