In [4]:
import numpy as np
import pandas as pd

In [7]:
# Soal 1

# Jika kode arr = np.arange(9).reshape(3, 3) dijalankan, maka akan menghasilkan output seperti berikut:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# Berdasarkan variabel arr di atas, apa code yang tepat untuk menghasilkan output
arr[:, [1, 2, 0]]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

In [11]:
# Soal 2 

# Tulis kode menggunakan numpy yang akan menghasilkan output seperti berikut:
np.random.randn(6).reshape(3, 2) # random distribusi normal

array([[-0.26799473, -1.65936572],
       [ 2.15312965, -1.64041551],
       [-0.81234685,  0.38344085]])

In [13]:
np.random.rand(6).reshape(3, 2) 

array([[0.54538891, 0.72022108],
       [0.02226992, 0.85873309],
       [0.60224386, 0.82434817]])

In [15]:
# randint : (low, high, size)
np.random.randint(10, 20, 10)

array([12, 14, 13, 17, 19, 11, 17, 14, 12, 16])

In [16]:
# Soal 3

# Bagaimanakah cara yang benar untuk menampilkan rata-rata harga rumah dengan 4 ruangan
df = pd.read_csv('melb_data.csv')
df.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [17]:
# cara 1: kolom - baris - function
df['Price'][df['Rooms']==4].mean()

1445281.7358630951

In [18]:
# cara 2: baris - kolom - function
df[df['Rooms']==4]['Price'].mean()

1445281.7358630951

In [20]:
# cara 3: baris - function - kolom
df[df['Rooms']==4].mean()['Price']

1445281.7358630951

In [21]:
df.loc[df['Rooms']==4, ['Price']].mean()

Price    1.445282e+06
dtype: float64

In [22]:
# Soal 4

# Kita memiliki Numpy array sebagai berikut:
d = np.arange(16).reshape(4, 4)
d



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
# Code apa yang kita gunakan jika ingin mengakses/menghasilkan output:
d[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
d[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [25]:
# Part 2

In [62]:
# Soal 1
# Jika kode x = np.arange(40).reshape(5, 8) dijalankan, maka akan menghasilkan:
arr = np.arange(40).reshape(5, 8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [65]:
arr[[0, 2, 4], 3:6] # arr[[baris], kolom]

array([[ 3,  4,  5],
       [19, 20, 21],
       [35, 36, 37]])

In [66]:
arr[[0, 2, 4], -5:-2] # dari belakang indexing kolom

array([[ 3,  4,  5],
       [19, 20, 21],
       [35, 36, 37]])

In [46]:
# Soal 2
# Perhatikan kode berikut:
df1 = pd.DataFrame(
    {
        'A':['A0', 'A1', 'A2', 'A3'],
        'B':['B0', 'B1', 'B2', 'B3'],
        'C':['C0', 'C1', 'C2', 'C3'],
        'D':['D0', 'D1', 'D2', 'D3'],
    },
    index = [0, 1, 2, 3])

df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [47]:
df2 = pd.DataFrame(
    {
        'B':['B2', 'B3', 'B6', 'B7'],
        'D':['D2', 'D3', 'D6', 'D7'],
        'F':['F2', 'F3', 'F6', 'F7'],
    },
    index = [2, 3, 6, 7])

df2

B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

In [83]:
# Buatlah kode yang menghasilkan output seperti gambar berikut:
pd.concat([df1,df2], axis=1)[2:4]

A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

In [68]:
# Soal 3
np.random.seed(10)
arr = np.random.randint(20, size=(2, 4))
arr

array([[ 9,  4, 15,  0],
       [17, 16, 17,  8]])

In [73]:
arr1 = arr[1, 1:3] # baris 2 dan kolom 2 sampai 3
arr1

array([16, 17])

In [74]:
arr2 = arr[0:3, 2] # baris 1 sampai 2 dan kolom 3
arr2

array([15, 17])

In [75]:
x = arr1 + arr2
x

array([31, 34])

In [57]:
# Soal 4
# menggunakan melbourne Housing dataset, bagaimana caranya (code)
# agar dapat menampilkan jumlah tipe kamar yang terdapat pada dataset tersebut

In [76]:
df['Rooms'].value_counts()

3     5881
2     3648
4     2688
1      681
5      596
6       67
7       10
8        8
10       1
Name: Rooms, dtype: int64

In [79]:
len(pd.unique(df['Rooms']))

9

In [81]:
df['Rooms'].nunique()

9